# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: faulhaber.IT
email: sebastian.faulhaber@gmx.de
author:
  name: Sebastian Faulhaber
  twitter: faulhaber_IT
  picture: /assets/images/author.jpeg
  links:
    - title: LinkedIn
      url: https://www.linkedin.com/in/sebastianfaulhaber/
      icon: fab fa-brands fa-linkedin
    - title: Twitter
      url: https://twitter.com/faulhaber_IT
      icon: fab fa-twitter-square
#description: >- # this means to ignore newlines until "baseurl:"
#  Open Leadership, cloud technology and a growth mindset create a better future.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.faulhaber.it" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title:output_ext

# Build settings
#theme: minima 
# https://github.com/mmistakes/so-simple-theme/tree/master
remote_theme: mmistakes/so-simple-theme

# Minima Social Links
twitter_username: faulhaber_IT
github_username: sebastianfaulhaber
linkedin_username: sebastianfaulhaber

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/sebastianfaulhaber/
    icon: fab fa-brands fa-linkedin
  - title: Twitter
    url: https://twitter.com/faulhaber_IT
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/sebastianfaulhaber
    icon: fab fa-github-square